name: Farmingapp
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  firebase_core: ^2.25.4
  firebase_auth: ^4.17.4
  cloud_firestore: ^4.15.4
  # Other Firebase dependencies you use
  intl: ^0.18.1  # Add this line for date formatting
  url_launcher: ^6.1.10  # Add this for launching Firebase console URLs
  rxdart: ^0.27.7  # Adds better stream handling

  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
    - assets/image1.png
    - assets/image2.png
    - assets/fertilizer1.png
    - assets/3d_avatar_12.png


